### Assignment 10

Himank Dave hjdave2@illinois.edu

Madhura Kulkarni msk10@illinois.edu

Breif Explanation:

1) Where did you get the dataset?

A: The Buildings dataset can be found at https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/main/data/building_inventory.csv.

2) What is the data trying to measure?

A: Buildings Inventory Data is telling us about the building status, address, details of its owner, square footage, number of floors and its current status of operation.

3) What are you trying to show in the plot?

A: WE have plotted two interactive Plots describing the square footage per county, and number of floors under usage per category. In this plot if you hower above the bar chart you can see a drop down menu describing the details of that paticular plot. Which gives us quicker understanding of figures. Reason I have chosen horizontal since putting all counties on X axis won’t be that good looking. I have used colors like blue and green because they catch to eye really good. I have kept it very simple as i am quite new to using altair. If given more time I would like to play around visualization make it interactive using ipywidgets and other interactive plot tools that we can use in altair.

4) What vega-lite mark(s) you used and why?

A: The mark that was used was “bar” to depict the trend in data. With tooltip : content as data, to show give us an Interactive Horizontal Bar Chart.

In [1]:
import altair as alt
import pandas as pd

In [2]:
alt.Chart.from_dict?

In [3]:
url = "https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/main/data/building_inventory.csv"
buildings = pd.read_csv(url)

In [4]:
buildings

,Agency Name,Location Name,Address,City,Zip code,County,Congress Dist,Congressional Full Name,Rep Dist,Rep Full Name,...,Bldg Status,Year Acquired,Year Constructed,Square Footage,Total Floors,Floors Above Grade,Floors Below Grade,Usage Description,Usage Description 2,Usage Description 3
0,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,1975,1975,144,1,1,0,Unusual,Unusual,Not provided
1,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided
2,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided
3,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided
4,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8857,Department of Transportation,Belvidere Maintenance Storage Facility - Boone...,9797 Illinois Rte. 76,Belvidere,61008,Boone,16,Adam Kinzinger,69,Sosnowski Joe,...,In Use,0,0,432,1,0,0,Storage,NaN,NaN
8858,Department of Transportation,Belvidere Maintenance Storage Facility - Boone...,9797 Illinois Rte 76,Belvidere,61008,Boone,16,Adam Kinzinger,69,Sosnowski Joe,...,In Use,0,0,330,1,0,0,Storage,NaN,NaN
8859,Department of Transportation,Quincy Maintenance Storage Facility,800 Koch's Lane,Quincy,62305,Adams,18,Darin M. LaHood,94,Frese Randy E.,...,In Use,0,1987,130,1,0,0,Storage,High Hazard,NaN
8860,Illinois Community College Board,Illinois Valley Community College - Oglesby,815 North Orlando Smith Avenue,Oglesby,61348,LaSalle,16,Adam Kinzinger,76,Long Jerry Lee,...,In Use,1971,1971,49552,1,1,0,Education,Education,Not provided
8861,Department of Military Affairs,Peoria Army Aviation Support Facility,2323 S. Airport Rd,Peoria,61607,Peoria,17,Cheri Bustos,92,Gordon-Booth Jehan,...,In Progress,0,2017,288,1,0,0,Utiility & Miscellan,Utiility & Miscellan,NaN

In [5]:
buildings.describe()

,Zip code,Congress Dist,Rep Dist,Senate Dist,Year Acquired,Year Constructed,Square Footage,Total Floors,Floors Above Grade,Floors Below Grade
count,8862.000000,8862.000000,8862.000000,8862.000000,8862.000000,8862.000000,8.862000e+03,8862.000000,8862.000000,8862.000000
mean,61821.076845,13.404085,92.303318,46.408599,1913.267660,1906.135184,1.147603e+04,1.636087,1.449334,0.161589
std,1095.203357,4.037936,23.568457,11.781038,337.024796,351.180642,3.817263e+04,1.537603,1.286898,0.392717
min,1235.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,61105.000000,12.000000,79.000000,40.000000,1957.000000,1953.000000,2.330000e+02,1.000000,1.000000,0.000000
50%,62023.000000,14.000000,97.000000,49.000000,1975.000000,1974.000000,1.600000e+03,1.000000,1.000000,0.000000
75%,62650.000000,16.000000,110.000000,55.000000,1992.000000,1991.000000,6.426500e+03,2.000000,1.000000,0.000000
max,68297.000000,18.000000,119.000000,60.000000,2019.000000,2019.000000,1.200000e+06,31.000000,30.000000,4.000000

In [6]:
buildings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8862 entries, 0 to 8861
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Agency Name              8862 non-null   object
 1   Location Name            8862 non-null   object
 2   Address                  8811 non-null   object
 3   City                     8862 non-null   object
 4   Zip code                 8862 non-null   int64
 5   County                   8837 non-null   object
 6   Congress Dist            8862 non-null   int64
 7   Congressional Full Name  8699 non-null   object
 8   Rep Dist                 8862 non-null   int64
 9   Rep Full Name            8839 non-null   object
 10  Senate Dist              8862 non-null   int64
 11  Senator Full Name        8839 non-null   object
 12  Bldg Status              8862 non-null   object
 13  Year Acquired            8862 non-null   int64
 14  Year Constructed         8862 non-null   int64
 15  Square Footage           8862 non-null   int64
 16  Total Floors             8862 non-null   int64
 17  Floors Above Grade       8862 non-null   int64
 18  Floors Below Grade       8862 non-null   int64
 19  Usage Description        8862 non-null   object
 20  Usage Description 2      8832 non-null   object
 21  Usage Description 3      8774 non-null   object
dtypes: int64(10), object(12)
memory usage: 1.5+ MB

In [7]:
buildings = buildings.dropna()

In [ ]:
buildings.hist(figsize=(15, 10))

## EDA:
1. There was presnce of null values, whihc was dropped from the dataset.
2. From a deeper look at the description of ananlysis and histogarm that we have plotted we can create two vizualizations,
   i.e. Square Footage per County and Number of floors per Usage Category.
3. Building Dataset consists of 22 columns and 8862 rows


   
   For Vizualization we intend to use altair object which is defined as alt.

In [ ]:
chart1 = alt.Chart.from_dict(
{
  'data': {"url": "https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/main/data/building_inventory.csv"
  }, 
  'width' : 250,
  'height' : 1000,
  'title': "Sqaure Footage per County",
  'mark': {"type":"bar", "tooltip": {"content": "data"}},
  'encoding': {
    "x": {"aggregate": "sum", "field": "Square Footage", "type": "quantitative", "title": "Square Footage"},
    "y": {"field": "County", "type": "nominal"},
    "color": {"value": "green"}
  }
}).interactive()

In [ ]:
chart1

This Plot is an Interactive plot of Square Footage per counties in the state of Illinois,From the look at ot we find Cook County has higher number of Square Footage folowed by Champaign and Sangamon.

In [ ]:
myJekyllDir = r'C:\Users\PC\kmadhura08.github.io\assets\json\json'

In [ ]:
chart1.properties(width='container').save(myJekyllDir+'sq_footage.json')
# note the "container" property allows us to resize the visualization 
# when the page is resized

In [ ]:
chart2 = alt.Chart.from_dict(
{
  'data': {"url": "https://uiuc-ischool-dataviz.github.io/spring2019online/week02/building_inventory.csv"
  }, 
  'width' : 800,
  'height' : 350,
  'title': "Number of Floors per Usage Category",
  'mark': {"type":"bar", "tooltip": {"content": "data"}},
  'encoding': {
    "x": {"aggregate": "sum", "field": "Total Floors", "type": "quantitative", "title": "Number of Floors"},
    "y": {"field": "Usage Description", "type": "nominal"},
    "color": {"value": "blue"}
  }
}).interactive()

In [ ]:
chart2

This Plot is an Interactive plot of Number of Floors per Usage Category in the state of Illinois,From the look atiot we find Storage has high number of flors that are under use which makes sense.

In [ ]:
chart2.properties(width='container').save(myJekyllDir+'floors.json')
# note the "container" property allows us to resize the visualization 
# when the page is resized